version: 1.1.0-ALPHA
author: MauriceLPs
name: LotusGamingSystem
main: eu.lotusgc.mc.main.Main
api-version: 1.21

commands:
    build:
    spawn:
    spawn-admin:
    bankwithdraw:
    bankdeposit:
    topbal:
        aliases: topbalance
    pay:
    money:
    deleteserversign:
        aliases: delss